# -*- coding: utf-8 -*-
"""Linear-Regression Salary ML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mTI5-gIiyC4kYxCpcl57dNXTIxcj5oOm
"""

import pandas as pd

df = pd.read_csv("LSM1.csv")

df

x = df.iloc[:,0].values.reshape(5,1)
y = df.iloc[:,1].values

x.shape

x

y

from sklearn.linear_model import LinearRegression

lin = LinearRegression()

lin.fit(x,y)

import matplotlib.pyplot as plt

y_pred = lin.predict(x)

plt.scatter(x,y)
plt.plot(x,y_pred, color = "green")
plt.show()

lin.predict([[2.5]])

plt.scatter(x,y)
plt.plot(x,y_pred, color = 'green')
plt.show()

"""# New Section"""