# -*- coding: utf-8 -*-
"""Logistic_Regression ML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lMtFkIGC4EIQ5UNVEs1ob-zUOBImv7fs
"""

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Social_Network_Ads.csv")

df

x = df.iloc[:,2:4].values
y = df.iloc[:,4].values

x

y

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.25, random_state=0)

x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

x_test

from sklearn.linear_model import LogisticRegression

log = LogisticRegression(random_state=0)

log.fit(x_train,y_train)

pred_y = log.predict(x_test)

pred_y

y_test

from sklearn import metrics

metrics.accuracy_score(y_test,pred_y)

metrics.confusion_matrix(y_test,pred_y)

log.predict(sc.transform([[32,70000]]))